spring.datasource.url=jdbc:mysql://localhost:3306/company_db2
spring.datasource.username=root
spring.datasource.password=Sahana@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.application.name=employeecrud
server.port=8081
